# Generated by Django 5.1.15 on 2026-04-22 01:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='应收金额')),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='实收汇总')),
                ('issue_date', models.DateField(verbose_name='应收日期')),
                ('due_date', models.DateField(verbose_name='到期日期')),
                ('status', models.CharField(choices=[('pending', '待收'), ('partial', '部分收款'), ('paid', '已收')], default='pending', max_length=16, verbose_name='状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivables', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='students.serviceplan', verbose_name='服务方案')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '应收记录',
                'verbose_name_plural': '应收记录',
                'ordering': ['status', 'due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='收款金额')),
                ('method', models.CharField(choices=[('bank', '银行转账'), ('wechat', '微信'), ('alipay', '支付宝'), ('cash', '现金'), ('other', '其他')], default='bank', max_length=16, verbose_name='收款方式')),
                ('received_at', models.DateTimeField(verbose_name='收款时间')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_entries', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payments.receivable', verbose_name='应收记录')),
            ],
            options={
                'verbose_name': '实收流水',
                'verbose_name_plural': '实收流水',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['status', 'due_date'], name='receivable_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['student', 'due_date'], name='receivable_student_due_idx'),
        ),
        migrations.AddIndex(
            model_name='paymententry',
            index=models.Index(fields=['received_at'], name='payment_entry_received_idx'),
        ),
    ]
