# Generated by Django 5.1.15 on 2026-04-22 01:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('unknown', '未说明'), ('male', '男'), ('female', '女')], default='unknown', max_length=16, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('parent_phone', models.CharField(blank=True, max_length=32, verbose_name='家长联系方式')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=255, verbose_name='标签')),
                ('source_channel', models.CharField(blank=True, max_length=64, verbose_name='来源渠道')),
                ('status', models.CharField(choices=[('lead', '潜在'), ('active', '在读/服务中'), ('paused', '暂停'), ('closed', '结束')], default='active', max_length=16, verbose_name='状态')),
                ('service_type', models.CharField(blank=True, max_length=64, verbose_name='服务类型')),
                ('risk_flag', models.CharField(blank=True, max_length=64, verbose_name='风险标记')),
                ('attention_note', models.TextField(blank=True, verbose_name='重点关注')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='执行账号')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=128, verbose_name='科目/咨询类型')),
                ('settlement_mode', models.CharField(choices=[('package', '课包制'), ('per_session', '按次结算')], max_length=32, verbose_name='结算模式')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='单价')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='总课时')),
                ('remaining_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='剩余课时')),
                ('owed_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='欠课时')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前生效')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '服务方案',
                'verbose_name_plural': '服务方案',
                'ordering': ['-is_active', '-effective_from', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='student_name_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone'], name='student_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('name', 'phone'), name='uniq_student_name_phone'),
        ),
        migrations.AddIndex(
            model_name='serviceplan',
            index=models.Index(fields=['student', 'is_active'], name='plan_student_active_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceplan',
            index=models.Index(fields=['settlement_mode'], name='plan_settlement_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='uniq_active_plan_per_student'),
        ),
    ]
