# Generated by Django 5.1.15 on 2026-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('lead', '潜在'), ('active', '服务中'), ('paused', '暂停'), ('closed', '结束')], default='active', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tags',
            field=models.CharField(blank=True, help_text='使用逗号分隔多个标签', max_length=255, verbose_name='标签'),
        ),
    ]
