# Generated by Django 5.1.15 on 2026-04-22 01:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_status', models.CharField(choices=[('present', '正常出勤'), ('partial', '部分出勤'), ('absent', '缺勤'), ('leave', '请假')], max_length=16, verbose_name='实际出勤')),
                ('actual_duration_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='实际时长（小时）')),
                ('deducted_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='扣减课时')),
                ('remaining_hours_after', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='扣减后剩余课时')),
                ('owed_hours_added', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='新增欠课时')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_sessions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='schedules.schedule', verbose_name='排课')),
            ],
            options={
                'verbose_name': '完成记录',
                'verbose_name_plural': '完成记录',
                'ordering': ['-schedule__start_at'],
            },
        ),
    ]
