# Generated by Django 5.1.15 on 2026-05-26 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='链路追踪ID')),
                ('feature_name', models.CharField(db_index=True, max_length=64, verbose_name='功能模块')),
                ('input_parameters', models.JSONField(blank=True, default=dict, verbose_name='输入参数')),
                ('raw_prompt', models.TextField(verbose_name='原始提示词')),
                ('raw_response', models.TextField(verbose_name='原始响应内容')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='输入Token数')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='输出Token数')),
                ('input_tokens_cached', models.PositiveIntegerField(default=0, verbose_name='缓存命中Token数')),
                ('latency_ms', models.PositiveIntegerField(verbose_name='响应耗时(毫秒)')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='预估成本(USD)')),
                ('cache_hit_rate', models.FloatField(default=0.0, verbose_name='缓存命中率')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='调用时间')),
            ],
            options={
                'verbose_name': 'AI 审计日志',
                'verbose_name_plural': 'AI 审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
