# Generated by Django 5.1.15 on 2026-04-22 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_enabled', models.BooleanField(default=True, verbose_name='启用课程提醒')),
                ('course_lead_minutes', models.PositiveIntegerField(default=60, verbose_name='课程提前提醒分钟')),
                ('receivable_enabled', models.BooleanField(default=True, verbose_name='启用待收款提醒')),
                ('receivable_due_offset_days', models.PositiveIntegerField(default=0, verbose_name='到期偏移天数')),
            ],
            options={
                'verbose_name': '提醒配置',
                'verbose_name_plural': '提醒配置',
            },
        ),
        migrations.CreateModel(
            name='ReminderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('reminder_type', models.CharField(choices=[('course', '课程提醒'), ('receivable', '待收款提醒')], max_length=16, verbose_name='提醒类型')),
                ('remind_at', models.DateTimeField(verbose_name='提醒时间')),
                ('status', models.CharField(choices=[('pending', '未完成'), ('done', '已完成')], default='pending', max_length=16, verbose_name='执行状态')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('message', models.TextField(verbose_name='提醒内容')),
                ('window_key', models.CharField(max_length=255, unique=True, verbose_name='去重键')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '提醒任务',
                'verbose_name_plural': '提醒任务',
                'ordering': ['status', 'remind_at', 'id'],
                'indexes': [models.Index(fields=['status', 'remind_at'], name='reminder_status_time_idx')],
            },
        ),
    ]
