# Generated by Django 5.1.15 on 2026-04-22 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson_sessions', '__first__'),
        ('schedules', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(verbose_name='课后情况')),
                ('next_focus', models.TextField(blank=True, verbose_name='下次重点')),
                ('internal_note', models.TextField(blank=True, verbose_name='内部备注')),
                ('completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lesson_sessions.lessonsession', verbose_name='完成记录')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_notes', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='schedules.schedule', verbose_name='排课')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '课后备注',
                'verbose_name_plural': '课后备注',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
