# Generated by Django 5.1.15 on 2026-04-22 01:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='标题')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25'))], verbose_name='时长（小时）')),
                ('status', models.CharField(choices=[('pending', '待上课'), ('completed', '已完成'), ('canceled', '已取消'), ('rescheduled', '已改期')], default='pending', max_length=16, verbose_name='状态')),
                ('delivery_mode', models.CharField(choices=[('online', '线上'), ('offline', '线下')], default='online', max_length=16, verbose_name='上课方式')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='地点/链接')),
                ('recurrence_group', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='系列分组')),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, verbose_name='系列规则')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_schedules', to=settings.AUTH_USER_MODEL, verbose_name='执行账号')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='students.serviceplan', verbose_name='服务方案')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '排课',
                'verbose_name_plural': '排课',
                'ordering': ['start_at', 'id'],
                'indexes': [models.Index(fields=['start_at'], name='schedule_start_idx'), models.Index(fields=['status'], name='schedule_status_idx'), models.Index(fields=['owner', 'start_at'], name='schedule_owner_start_idx'), models.Index(fields=['student', 'start_at'], name='schedule_student_start_idx')],
            },
        ),
    ]
